apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weather-app-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/weather-app-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: VITE_API_URL
          value: "https://weather-app-backend-HASH-uc.a.run.app"
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
  traffic:
  - percent: 100
    latestRevision: true