apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weather-app-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/weather-app-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "__DB_HOST__"
        - name: DB_PORT
          value: "__DB_PORT__"
        - name: DB_USER
          value: "__DB_USER__"
        - name: DB_PASSWORD
          value: "__DB_PASSWORD__"
        - name: DB_NAME
          value: "__DB_NAME__"
        - name: OPENWEATHER_API_KEY
          value: "__OPENWEATHER_API_KEY__"
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
  traffic:
  - percent: 100
    latestRevision: true