version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3001
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - PORT=3001
