version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
